--This file was automatically generated by the Telltale Script Editor, available at https://github.com/Telltale-Modding-Group/Telltale-Script-Editor"
--File assocated with 'First Cutscene Mod' by changemymindpls1, version 1.0
local set = {}
set.name = "FCMAssetsFirstCutsceneMod"
set.setName = "FCMAssetsFirstCutsceneMod"
set.descriptionFilenameOverride = ""
set.logicalName = "<>" --Empty for now, band-aid fix for later.
set.logicalDestination = "<>"
set.priority = 1100
set.localDir = _currentDirectory
set.enableMode = "bootable"
set.version = "trunk"
set.descriptionPriority = 0
set.gameDataName = "FCMAssetsFirstCutsceneMod Game Data"
set.gameDataPriority = 1100
set.gameDataEnableMode = "constant"
set.localDirIncludeBase = true
set.localDirRecurse = false
set.localDirIncludeOnly = nil
set.localDirExclude =
{
    "Packaging/",
    "_dev/"
}
set.gameDataArchives =
{
    _currentDirectory .. "FCM_Assets_FirstCutsceneMod.ttarch2"
}
RegisterSetDescription(set)